language: java
matrix:
  include:
    - name: "Ubuntu Bionic with OpenJDK 12"
      dist: bionic
      jdk: openjdk12
      services: xvfb
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/khaiii-orig
          - $HOME/.hunter
    - name: "OSX with OpenJDK 12"
      os: osx
      osx_image: xcode10.2
      language: shell
      jdk: openjdk12
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/khaiii-orig
          - $HOME/.hunter
    - name: "Windows with OpenJDK 12"
      os: windows
      language: shell
      filter_secrets: false
      before_install:
        - choco install openjdk --version 12.0.0 -y
        - java --version
      env:
        - JAVA_HOME="/c/Progra~1/OpenJDK/jdk-12"
        - PATH="$JAVA_HOME/bin:$PATH"
before_install:
  - openssl aes-256-cbc -K $encrypted_61168456aa19_key -iv $encrypted_61168456aa19_iv -in deploy.key.enc -out deploy.key -d
  - chmod 600 deploy.key
  - eval `ssh-agent -s`
  - ssh-add deploy.key
install:
  - bash khaiii/install.sh
  - bash utagger/install.sh
script:
  - ./gradlew clean
  - ./gradlew check -Parch=$TRAVIS_OS_NAME -PnoGUI --info
  - if [ $TRAVIS_OS_NAME == 'linux' ]
    then
    xvfb-run -a ./gradlew :koalanlp-rhino:test :koalanlp-rhino:jacocoTestReport --tests *OriginTest --info
    fi
after_success:
  - bash ./git-manage.sh
env:
  global:
    - secure: C5rYSRoBPS7vbgxD8SKQ9bVqzYHmNDM3ccQQ3fbMrieTUibfBv31Lf9973mrp7gOiqldj7mu/G0ERVz8eSD5HY8KhXwG+WFtE604UWzDXW2Qh+/FNhtP2ogBpF5yIjToJKXMyfKivSlCUQwRa1cUsuzHi6xlY2oWLBSUA0nsRqzNxEx2bXsl1eXdR8Xe2iea9k1EZJZeH+MnHNlrI4WieEFra0fgpOHflG3DRyIRnniNYt3acWm1Jgu1WwFy+eFaTANsTmrb1sQMXhbmchYHp0QnyGE3KSoYLY2BGEC/Zs/o+2b1dSSI+rVBoY6TuS6orR80agnf7D97ip1ILXDnqbo+gM2QHLBgYxdjoWjpC07aeUyAX3/niWXruu54dtix/TjAzs5MBI2a0tA7d+1RPE665/KcjnvMLusutHwd5RqDSYsfJR4sHudniGUEc+goXCckSbE1SCkGM7GFJBazvNNeYR6rJPQJzOh3ISR3uVDzFTXEBRM8sPctBmveebj1uCuZTv19JfEEGB7x6PJEfhFQibH6kcTWqTz85rGJ2uOvjVkm0y4aRBaLY9ZV5ldtBfv8CCVvTV8+CLNYV7/x7/WFYs/G9BRtmqvFWlgqJ3td5ga9foaGNYuD7UM0JsHVqWjMoCe5eiPH4vz3Rf5DWFVkSOcCAUYYYDcHVQQPywE=
    - secure: Ao8FfgHXzEwJdq1ZVzbFRYIxZqr+Beb8LsmE5EiTthotJ4AFh/QDTWObl+K61a7cLg2UhqvToCCNAFmSxYirSGX9QizGOGz8qSbm6alojHOQ6+zztrlN0+avYuYddpiDwWxGk2aGy0H88xmjSbwiBXEQ8FpZ21E2aK1vaaFOsyqiMsAx4ZVmA/0o6VzghR1OUR9K3ghY0wxKpqkL1vpmeSErlHTE4JRWJL6+A7aQRvdLf1lgTiCNYJrv2ITRH49+ONDp6OwbFPMF8clHVrmJne0bqP7z7PSR+bsegdViCQ8Dck3awfaOvZtcDC1ZNnNCZaCw+S4ER907PsYq+0mobL2IbcXBJDfand2DWPhiGGaJKASE74MjRj6g91Oz6/sAZVIgvxxfOkdXZ2UeMJiM5MEbu1zpt5a8jIOAjK2z6Mn/+Fq3ae0DR/KWdERwFaIXbNgVr4ODoerNPXZkjfRNm6GhOINb1iVIAqgj10ZT/2hTzFwYY/5UH155gzACzyBAx6pI2S5CzwJNvFCVFWolABfeV0eUYJLeoAnX2aMaPKss5CgnA4nNuoVHMeQa8wQdzL81u+XT8YOSrYr5NEhoIpohJZJKBcXDWO7zvrhloUWsPbRfe++gmUNB6hHOAYw0INztDObI66nK2YiQ49a8E7XBMuVb55hIC+Q+ifiO4e8=
    - secure: TV4eSBdZwm9yXJKO93211xouu46lIbnFlskQpu9+JJsMikETbN9eymyOWd0/W8SLTNZxB0BW0XiKkUuk89e1ZSRsfFm4xJFRCgAmN1IYxypjEYNloJeGALmvU841iW0BjORRgNnLntsB6wO4LtI/piysBh/ygkrFKnvRPFX+hDIx1iYPC5xcN7Sihvo3lEQVPbh2IOrKYfKM83gUEzxlJvdIgRNkSGi+7u7ryjEl8/bizU23mUkHW7SWcCFPLaxL/Ysf2KI9Ko66a5KEHQ2JR9wRCDcUlWWOXsojMfa4Sy7f8IcimL+8XVzX/oPpnp4jfVfJhdIzw5+06km53Ipp6Yza4JmylxLwR2q6hC1Bu45SwE1gCwmI4BHsxLHfEhC0l6h5hPbjt2zm/2teyVm3ETmznuWArd0Dt7nE1i1g+aIQ8CHrEVFdLUHjKs+T5+EVNj4e/QpsVeTZygGwmx3GbQgPeeCBmz8mQ9xMm5oAVaVnH1Bg4ROfr6U8HJ25bpNgxLee5suajNQpqoTP60octJjFN1ILqTGdPhzYLECeboLKkTrq/+W/nou1yjSg5vUa5eBd0Mh2+kelrUkrv7Rue2zEappg+xlZ/10nhGk6VOyzIoqyfiztnbT8SfgJ3JZi1rYoszMCH4Nk1qxjJdVdVQLaoCpStZJ/sl69EAHfHq4=
    - KHAIII_RSC=$HOME/khaiii-orig/build/share/khaiii
    - KHAIII_LIB=$HOME/khaiii-orig/build/lib
